@clientid =pipo
@clientsecret = 
### list all messages 


GET http://localhost:1337/api/concerts


### post rq 

POST /api/concerts?title=consert2 HTTP/1.1
Host: localhost:1337
Authorization: Bearer 6925b3f6dd10f22101c73efed49acb7c0a00dd408033af17b30d32c8380a47ad492cda73076a12aa77e81186ffa78b828595dc78dd102f5c31f55f4ccb28e0ab430714a1c6475c2eede99aeeac25308c282dd4c6fbdc34a668ecb5fb047a939ec032d79fd8f5584356098d6a67e80c6a2c7d5828a25416d1a439611e5fcb2302
Content-Type: application/json
Content-Length: 619

{
  "data": {
    "title": "Rock Revolution Showcase",
    "date": "2024-03-10",
    "time": "20:00:00",
    "venue": "Thunder Dome",
    "state": "California",
    "country": "USA",
    "genre": "rock",
    "description": [
      {
        "type": "paragraph",
        "children": [
          {
            "text": "Get ready for an electrifying night of pure rock energy at the Thunder Dome. Join us as we showcase the best rock bands in California. Experience the power of live performances and unforgettable guitar solos.",
            "type": "text"
          }
        ]
      }
    ]
  }
}

### new post 



